### ISSUE TITLE
Devalart watermarks

### ISSUE THREAD

**Issue by Epicnoobie** [Viper-Development-Team/viper-website#3]
We can't have people seeing this. But yes tell people in Caleb's intro that he made all the art work ![image](https://user-images.githubusercontent.com/65642742/88869944-1dbd9800-d1e2-11ea-8ce1-fa340eb1041d.jpeg)![image](https://user-images.githubusercontent.com/65642742/88869959-231ae280-d1e2-11ea-9f14-f43261cec8ab.jpeg)also when do you think this will be made in mobile like how do you do that

**Comment by gitozify** [comment]
> We can't have people seeing this. But yes tell people in Caleb's intro that he made all the art work ![image](https://user-images.githubusercontent.com/65642742/88869944-1dbd9800-d1e2-11ea-8ce1-fa340eb1041d.jpeg)![image](https://user-images.githubusercontent.com/65642742/88869959-231ae280-d1e2-11ea-9f14-f43261cec8ab.jpeg)also when do you think this will be made in mobile like how do you do that

First off, please don't post random Issues, even though you're a creator.
Secondly, I'm not working on the site as much, until we get everything sorted out for pages then I will try and make it fit for mobile, however, that topic is for another day. **CLOSED**
