### ISSUE TITLE
Devalart page

### ISSUE THREAD

**Issue by DevalartOfficial** [Viper-Development-Team/viper-website#8]
Devalart's page doesn't have anything on it. Please fix this <3

**Comment by gitozify** [comment]
> Devalart's page doesn't have anything on it. Please fix this <3

Okay that's a reasonable Issue, I got everything ready for you so I will try and upload them.

**Comment by DevalartOfficial** [comment]
A man has fallen into the river

**Comment by DevalartOfficial** [comment]
A man has fallen into the river

**Comment by gitozify** [comment]
> A man has fallen into the river

No.

**Comment by DevalartOfficial** [comment]
A man has fallen into the man in man



start the man



man!


drive man
